const API=localStorage.getItem('duxue_api')||'http://localhost:8000';
const $=id=>document.getElementById(id);
let token=sessionStorage.getItem('duxue_token');
async function request(path,options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error((await response.json()).detail||`HTTP ${response.status}`);return response.status===204?null:response.json()}
function show(authenticated){$('login').classList.toggle('hidden',authenticated);$('dashboard').classList.toggle('hidden',!authenticated);$('logout').classList.toggle('hidden',!authenticated)}
async function load(){try{const [summary,wards]=await Promise.all([request('/admin/summary'),request('/wards')]);const labels={wards:'Ward 数',devices:'设备数',online_devices:'在线设备',frames_pending:'待分析帧',reports:'报告数'};$('metrics').innerHTML=Object.entries(labels).map(([key,label])=>`<div class="metric"><span class="muted">${label}</span><b>${summary[key]}</b></div>`).join('');const rows=await Promise.all(wards.map(async ward=>({ward,devices:await request(`/wards/${ward.id}/devices`)})));$('wards').innerHTML=rows.length?rows.map(({ward,devices})=>`<div class="ward"><strong>${escapeHtml(ward.display_name)}</strong><span>${devices.length?devices.map(d=>`<span class="${d.status}">${d.status==='online'?'在线':'离线'}</span>`).join(' · '):'<span class="muted">未绑定设备</span>'}</span></div>`).join(''):'<span class="muted">暂无 Ward</span>';show(true)}catch(error){sessionStorage.removeItem('duxue_token');token=null;show(false);$('login-error').textContent=error.message}}
function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}
$('login-form').addEventListener('submit',async event=>{event.preventDefault();$('login-error').textContent='';try{const response=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const body=await response.json();if(!response.ok)throw new Error(body.detail);token=body.access_token;sessionStorage.setItem('duxue_token',token);await load()}catch(error){$('login-error').textContent=error.message}});
$('refresh').onclick=load;$('logout').onclick=()=>{sessionStorage.clear();token=null;show(false)};if(token)load();else show(false);
