"""Create the initial Duxue server schema.

Revision ID: 20260804_01
Revises:
Create Date: 2026-08-04
"""
from alembic import op
import sqlalchemy as sa


revision = "20260804_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("tenants", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(100), nullable=False), sa.Column("plan", sa.String(30), nullable=False, server_default="self_hosted"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])
    op.create_index("ix_users_type", "users", ["type"])
    op.create_table("user_guardians", sa.Column("id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("name", sa.String(100), nullable=False), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(20), nullable=False, server_default="guardian"), sa.CheckConstraint("role IN ('admin', 'guardian')", name="ck_guardian_role"))
    op.create_index("ix_user_guardians_email", "user_guardians", ["email"])
    op.create_table("analysis_profiles", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("created_by", sa.String(36), sa.ForeignKey("user_guardians.id"), nullable=False), sa.Column("name", sa.String(100), nullable=False), sa.Column("extra_observation_prompt", sa.Text(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_analysis_profiles_tenant_id", "analysis_profiles", ["tenant_id"])
    op.create_table("user_wards", sa.Column("id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("display_name", sa.String(100), nullable=False), sa.Column("notes", sa.Text()), sa.Column("analysis_profile_id", sa.String(36), sa.ForeignKey("analysis_profiles.id")))
    op.create_index("ix_user_wards_tenant_id", "user_wards", ["tenant_id"])
    op.create_table("guardian_ward_relations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("guardian_id", sa.String(36), sa.ForeignKey("user_guardians.id", ondelete="CASCADE"), nullable=False), sa.Column("ward_id", sa.String(36), sa.ForeignKey("user_wards.id", ondelete="CASCADE"), nullable=False), sa.UniqueConstraint("guardian_id", "ward_id"))
    op.create_index("ix_guardian_ward_relations_tenant_id", "guardian_ward_relations", ["tenant_id"])
    op.create_table("refresh_tokens", sa.Column("id", sa.String(36), primary_key=True), sa.Column("guardian_id", sa.String(36), sa.ForeignKey("user_guardians.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index("ix_refresh_tokens_guardian_id", "refresh_tokens", ["guardian_id"])
    op.create_table("behavior_label_configs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("profile_id", sa.String(36), sa.ForeignKey("analysis_profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("label_name", sa.String(100), nullable=False), sa.Column("field_prototypes", sa.JSON(), nullable=False), sa.Column("priority", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index("ix_behavior_label_configs_tenant_id", "behavior_label_configs", ["tenant_id"])
    op.create_index("ix_behavior_label_configs_profile_id", "behavior_label_configs", ["profile_id"])
    op.create_table("devices", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("ward_id", sa.String(36), sa.ForeignKey("user_wards.id", ondelete="CASCADE"), nullable=False), sa.Column("device_type", sa.String(30), nullable=False, server_default="android"), sa.Column("device_token_hash", sa.String(64), unique=True), sa.Column("status", sa.String(20), nullable=False, server_default="offline"), sa.Column("invite_code", sa.String(6)), sa.Column("invite_code_expires_at", sa.DateTime(timezone=True)), sa.Column("invite_failures", sa.Integer(), nullable=False, server_default="0"), sa.Column("capture_interval_seconds", sa.Integer(), nullable=False, server_default="15"), sa.Column("last_heartbeat_at", sa.DateTime(timezone=True)), sa.Column("bound_server_time", sa.DateTime(timezone=True)), sa.Column("bound_elapsed_realtime", sa.Integer()))
    op.create_index("ix_devices_tenant_id", "devices", ["tenant_id"]); op.create_index("ix_devices_ward_id", "devices", ["ward_id"]); op.create_index("ix_devices_invite_code", "devices", ["invite_code"])
    op.create_table("analysis_batches", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("batch_date", sa.Date(), nullable=False), sa.Column("provider_batch_id", sa.String(255)), sa.Column("status", sa.String(30), nullable=False, server_default="submitted"), sa.Column("frame_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("fallback_used", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.create_index("ix_analysis_batches_tenant_id", "analysis_batches", ["tenant_id"])
    op.create_table("frames", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("device_id", sa.String(36), sa.ForeignKey("devices.id", ondelete="CASCADE"), nullable=False), sa.Column("ward_id", sa.String(36), sa.ForeignKey("user_wards.id", ondelete="CASCADE"), nullable=False), sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.Column("oss_key", sa.String(500), unique=True), sa.Column("analyzed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("batch_id", sa.String(36), sa.ForeignKey("analysis_batches.id")), sa.Column("structured_fields", sa.JSON()), sa.Column("training_candidate", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("purge_after", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_frames_tenant_id", "frames", ["tenant_id"]); op.create_index("ix_frames_device_id", "frames", ["device_id"]); op.create_index("ix_frames_ward_id", "frames", ["ward_id"]); op.create_index("ix_frames_captured_at", "frames", ["captured_at"]); op.create_index("ix_frames_analyzed", "frames", ["analyzed"]); op.create_index("ix_frames_purge_after", "frames", ["purge_after"])
    op.create_table("frame_predictions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("frame_id", sa.String(36), sa.ForeignKey("frames.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("behavior_label", sa.String(100), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("source", sa.String(20), nullable=False, server_default="api"), sa.Column("model_version", sa.String(100), nullable=False, server_default="qwen3-vl-flash"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_frame_predictions_tenant_id", "frame_predictions", ["tenant_id"])
    op.create_table("behavior_segments", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("ward_id", sa.String(36), sa.ForeignKey("user_wards.id", ondelete="CASCADE"), nullable=False), sa.Column("report_date", sa.Date(), nullable=False), sa.Column("seg_start", sa.DateTime(timezone=True), nullable=False), sa.Column("seg_end", sa.DateTime(timezone=True), nullable=False), sa.Column("behavior_label", sa.String(100), nullable=False), sa.Column("frame_count", sa.Integer(), nullable=False), sa.Column("confidence_avg", sa.Float(), nullable=False))
    op.create_index("ix_behavior_segments_tenant_id", "behavior_segments", ["tenant_id"]); op.create_index("ix_behavior_segments_ward_id", "behavior_segments", ["ward_id"]); op.create_index("ix_behavior_segments_report_date", "behavior_segments", ["report_date"])
    op.create_table("reports", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("ward_id", sa.String(36), sa.ForeignKey("user_wards.id", ondelete="CASCADE"), nullable=False), sa.Column("report_date", sa.Date(), nullable=False), sa.Column("total_seconds", sa.Integer(), nullable=False, server_default="0"), sa.Column("label_breakdown", sa.JSON(), nullable=False), sa.Column("timeline_json", sa.JSON(), nullable=False), sa.Column("profile_changed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("status", sa.String(30), nullable=False, server_default="ready"), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "ward_id", "report_date"))
    op.create_index("ix_reports_tenant_id", "reports", ["tenant_id"]); op.create_index("ix_reports_ward_id", "reports", ["ward_id"]); op.create_index("ix_reports_report_date", "reports", ["report_date"])


def downgrade() -> None:
    for table in ("reports", "behavior_segments", "frame_predictions", "frames", "analysis_batches", "devices", "behavior_label_configs", "refresh_tokens", "guardian_ward_relations", "user_wards", "analysis_profiles", "user_guardians", "users", "tenants"):
        op.drop_table(table)
